# Generated by Django 3.2.3 on 2022-01-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foods', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Meals',
            },
        ),
    ]
