# Generated by Django 3.2.3 on 2022-01-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaz', '0002_topping_unique_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
