# Generated by Django 3.2.3 on 2022-01-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaz', '0004_remove_topping_unique_topping'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='topping',
            constraint=models.UniqueConstraint(fields=('pizza', 'name'), name='unique_topping'),
        ),
    ]
